// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Characters {
  _id: string;
  name: string;
  role?: string;
  house?: House;
  school?: School;
  __v: number;
  ministryOfMagic: boolean;
  orderOfThePhoenix: boolean;
  dumbledoresArmy: boolean;
  deathEater: boolean;
  bloodStatus: BloodStatus;
  species: string;
  boggart?: string;
  alias?: string;
  animagus?: string;
  wand?: string;
  patronus?: string;
}

export enum BloodStatus {
  HalfBlood = "half-blood",
  HalfGiant = "half-giant",
  Muggle = "muggle",
  MuggleBorn = "muggle-born",
  PureBlood = "pure-blood",
  QuarterVilla = "quarter-villa",
  Squib = "squib",
  Unknown = "unknown",
}

export enum House {
  Gryffindor = "Gryffindor",
  Hufflepuff = "Hufflepuff",
  Ravenclaw = "Ravenclaw",
  Slytherin = "Slytherin",
}

export enum School {
  BeauxbatonsAcademyOfMagic = "Beauxbatons Academy of Magic",
  DurmstrangInstitute = "Durmstrang Institute",
  HogwartsAcademyOfWitchcraftAndWizardry = "Hogwarts Academy of Witchcraft and Wizardry",
  HogwartsSchoolOfWitchcraftAndWizardry = "Hogwarts School of Witchcraft and Wizardry",
}
