// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Houses {
  _id: string;
  name: string;
  mascot: string;
  headOfHouse: string;
  houseGhost: string;
  founder: string;
  __v: number;
  school?: string;
  members: string[];
  values: string[];
  colors: string[];
}
