// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Spells {
  _id: string;
  spell: string;
  type: Type;
  effect: string;
  __v?: number;
}

export enum Type {
  Charm = "Charm",
  Curse = "Curse",
  Enchantment = "Enchantment",
  Hex = "Hex",
  Jinx = "Jinx",
  Spell = "Spell",
}
